const NOT_FOUND = '404';
const SERVER_ERROR = '500';
const BAD_REQUEST = '400';
const CREATED = '201';
const UNAUTHORIZED = '401';
const CONFLICT = '409';

module.exports = {
  NOT_FOUND, SERVER_ERROR, BAD_REQUEST, CREATED, UNAUTHORIZED, CONFLICT,
};
